apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-binding
  namespace: augustovicente
subjects:
  - kind: ServiceAccount
    name: augustovicente
    namespace: augustovicente
roleRef:
  kind: Role
  name: pod-access-role
  apiGroup: rbac.authorization.k8s.io
