apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: augustovicente
  name: pod-access-role
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get", "list", "watch"]
