apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs-system-metrics
  template:
    metadata:
      labels:
        app: srs-system-metrics
    spec:
      containers:
        - name: srs-system-metrics
          image: agvicentee/srs-system-metrics:latest
          resources:
            requests:
              memory: 2G
          ports:
            - containerPort: 8050
          env:
          - name: REDIS_HOST
            value: '192.168.121.187'
          - name: REDIS_PORT
            value: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: srs-systemmetrics-service
spec:
  selector:
    app: srs-system-mettrics
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
      nodePort: 30333
  type: NodePort
