apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srs-model
  template:
    metadata:
      labels:
        app: srs-model
    spec:
      containers:
        - name: srs-model
          image: agvicente/srs-model:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-storage
              mountPath: /app/shared
          env:
          - name: DATASET_PATH
            value: /app/shared/datasets/spotify/2023_spotify_ds1.csv
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: project2-pv2-augustovicente
---
apiVersion: v1
kind: Service
metadata:
  name: srs-model-service
spec:
  selector:
    app: srs-model
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
