apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs-frontend
  template:
    metadata:
      labels:
        app: srs-frontend
    spec:
      containers:
        - name: srs-frontend
          image: agvicente/srs-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-storage
              mountPath: /app/shared
          env:
            - name: DATASET_PATH
              value: /app/shared/datasets/spotify/2023_spotify_songs.csv
            - name: API_URL
              value: "aaaa"
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: project2-pv2-augustovicente
---
apiVersion: v1
kind: Service
metadata:
  name: srs-frontend-service
spec:
  selector:
    app: srs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30111
  type: NodePort
