apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: augustovicente
  name: project2-pv2-augustovicente
  labels:
    type: local
spec:
  selector:
    matchLabels:
      namespace: augustovicente
  capacity:
    storage: 1Gi
  storageClassName: default-storage-class
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/augustovicente/project-pv2
  resources:
    requests:
      storage: 1Gi
